theme: jekyll-theme-minimal
title: "Yuyu Luo"
description: "<p>Master Student @ CS</p><small>Email: luoyy18[at]mails.tsinghua.edu.cn</small><br><small>Office: 10-204, East Main Building, Tsinghua.</small>"
logo: "/img/yuyu.jpg" 