theme: jekyll-theme-minimal
title: "Yuyu Luo (骆昱宇)"
logo: "/img/yuyu.jpg"
description: "<p>The Hong Kong University of
Science and Technology (Guangzhou)</p><small>Email: yuyuluo[at]hkust-gz.edu.cn</small><br><small>Office: E2-615, HKUST(GZ)</small><br><br><a href='https://scholar.google.com/citations?user=FAjYJkQAAAAJ&hl=en' target='_blank'><img src='./img/Google.png' alt='Google Scholar' style='width: 10%; display:inline-block; margin: 0 auto;'/></a>"
